// <auto-generated />
using System;
using LoanReviewApi.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanReviewApi.Infrastructure.Migrations
{
    [DbContext(typeof(LoanReviewContext))]
    [Migration("20251113165419_ChangeFieldName")]
    partial class ChangeFieldName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AggRating")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("AmortizationTermInMonths")
                        .HasColumnType("real");

                    b.Property<string>("ApplicantCifNumber")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("Balance")
                        .HasColumnType("real");

                    b.Property<float?>("Beacon")
                        .HasColumnType("real");

                    b.Property<string>("BorrowerName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchOfficeId")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchOfficeText")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BrokerCompany")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CommitmentDate")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Date1")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("EffectiveRate")
                        .HasColumnType("real")
                        .HasColumnName("EffectiveRate");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExceptionFlag")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FundingDate")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("Income")
                        .HasColumnType("real");

                    b.Property<string>("InsuranceType")
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("IsLocked")
                        .HasColumnType("tinyint")
                        .HasColumnName("isLocked");

                    b.Property<float?>("LTV")
                        .HasColumnType("real");

                    b.Property<string>("LoanClass")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoanConformingIndicator")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("MaturityDate")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MortgageOfficerBp")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MortgageOfficerName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MortgageOfficerSkey")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NonConformingReason")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("Obs")
                        .HasColumnType("real");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("OriginalTdsRatio")
                        .HasColumnType("real");

                    b.Property<string>("PartnerId")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PartnerName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PrRating")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("PriorEncAmount")
                        .HasColumnType("real");

                    b.Property<float?>("PriorEncCount")
                        .HasColumnType("real");

                    b.Property<string>("ProductBusinessGroupCode")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProductText")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("ReasonCode")
                        .HasColumnType("real");

                    b.Property<string>("ReviewType")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("RiskScore")
                        .HasColumnType("real");

                    b.Property<byte[]>("SSMA_TimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("SSMA_TimeStamp");

                    b.Property<float?>("ScoringValue")
                        .HasColumnType("real");

                    b.Property<float?>("SecurityTypeCode")
                        .HasColumnType("real");

                    b.Property<string>("SecurityTypeDescription")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SpRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("StressTDS")
                        .HasColumnType("real");

                    b.Property<float?>("TermInMonths")
                        .HasColumnType("real");

                    b.Property<string>("UnderwriterSkey")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VariableRateFlag")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanDetailsComm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AggRating")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("AmortizationTermInMonths")
                        .HasColumnType("real");

                    b.Property<string>("ApplicantCifNumber")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("Balance")
                        .HasColumnType("real");

                    b.Property<float?>("Beacon")
                        .HasColumnType("real");

                    b.Property<string>("BorrowerName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchOfficeId")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchOfficeText")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BrokerCompany")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CommitmentDate")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Date1")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("EffectiveRate")
                        .HasColumnType("real");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExceptionFlag")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FundingDate")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("Income")
                        .HasColumnType("real");

                    b.Property<string>("InsuranceType")
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("IsLocked")
                        .HasColumnType("tinyint")
                        .HasColumnName("isLocked");

                    b.Property<float?>("LTV")
                        .HasColumnType("real");

                    b.Property<string>("LoanClass")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoanConformingIndicator")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("MaturityDate")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MortgageOfficerBp")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MortgageOfficerName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MortgageOfficerSkey")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NonConformingReason")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("Obs")
                        .HasColumnType("real");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("OriginalTdsRatio")
                        .HasColumnType("real");

                    b.Property<string>("PartnerId")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PartnerName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PrRating")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("PriorEncAmount")
                        .HasColumnType("real");

                    b.Property<float?>("PriorEncCount")
                        .HasColumnType("real");

                    b.Property<string>("ProductBusinessGroupCode")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProductText")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("ReasonCode")
                        .HasColumnType("real");

                    b.Property<string>("ReviewType")
                        .HasColumnType("nvarchar(255)");

                    b.Property<float?>("RiskScore")
                        .HasColumnType("real");

                    b.Property<byte[]>("SSMA_TimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("SSMA_TimeStamp");

                    b.Property<float?>("ScoringValue")
                        .HasColumnType("real");

                    b.Property<float?>("SecurityTypeCode")
                        .HasColumnType("real");

                    b.Property<string>("SecurityTypeDescription")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SpRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("StressTDS")
                        .HasColumnType("real");

                    b.Property<float?>("TermInMonths")
                        .HasColumnType("real");

                    b.Property<string>("UnderwriterSkey")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VariableRateFlag")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanDetailsComm");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanReviewDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("CompletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("isLocked");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("LoanDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("LoanDetailsCommId")
                        .HasColumnType("int");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompletedBy");

                    b.HasIndex("LastUpdatedBy");

                    b.HasIndex("LoanDetailId");

                    b.HasIndex("LoanDetailsCommId");

                    b.HasIndex("LoanId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TemplateId");

                    b.ToTable("LoanReviewDetails");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanReviewItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("TemplateItemId");

                    b.ToTable("LoanReviewItems");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanReviewReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CDCount")
                        .HasColumnType("int");

                    b.Property<int?>("DecisionCount")
                        .HasColumnType("int");

                    b.Property<int?>("L1Count")
                        .HasColumnType("int");

                    b.Property<int?>("L1L2Count")
                        .HasColumnType("int");

                    b.Property<int?>("L2Count")
                        .HasColumnType("int");

                    b.Property<int?>("L2OtherCount")
                        .HasColumnType("int");

                    b.Property<int?>("L2TDSIncCount")
                        .HasColumnType("int");

                    b.Property<int?>("RefCompCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoanReviewReports");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanReviewStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("LoanReviewStatuses");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OptionTypeId");

                    b.ToTable("ReviewOptions");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewOptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("ReviewOptionTypes");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("ReviewTemplates");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasComment")
                        .HasColumnType("bit")
                        .HasColumnName("hasComment");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnName("isDisabled");

                    b.Property<int?>("ItemOptionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ItemOptionTypeId");

                    b.ToTable("ReviewTemplateItems");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanReviewDetail", b =>
                {
                    b.HasOne("LoanReviewApi.Core.Models.Users.User", "UserCompletedBy")
                        .WithMany("UsersCreatedReviewDetails")
                        .HasForeignKey("CompletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LoanReviewApi.Core.Models.Users.User", "UserUpdatedBy")
                        .WithMany("UsersUpdatedReviewDetails")
                        .HasForeignKey("LastUpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LoanReviewApi.Core.Models.Loans.LoanDetail", "LoanDetail")
                        .WithMany("LoanReviewDetails")
                        .HasForeignKey("LoanDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanReviewApi.Core.Models.Loans.LoanDetailsComm", "LoanDetailsComm")
                        .WithMany("LoanReviewDetails")
                        .HasForeignKey("LoanDetailsCommId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LoanReviewApi.Core.Models.Loans.LoanReviewStatus", "LoanReviewStatus")
                        .WithMany("LoanReviewDetails")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LoanReviewApi.Core.Models.Reviews.ReviewTemplate", "ReviewTemplate")
                        .WithMany("LoanReviewDetails")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LoanDetail");

                    b.Navigation("LoanDetailsComm");

                    b.Navigation("LoanReviewStatus");

                    b.Navigation("ReviewTemplate");

                    b.Navigation("UserCompletedBy");

                    b.Navigation("UserUpdatedBy");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanReviewItem", b =>
                {
                    b.HasOne("LoanReviewApi.Core.Models.Reviews.ReviewOption", "ReviewOption")
                        .WithMany("LoanReviewItems")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LoanReviewApi.Core.Models.Loans.LoanReviewDetail", "LoanReviewDetail")
                        .WithMany("LoanReviewItems")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LoanReviewApi.Core.Models.Reviews.ReviewTemplateItem", "TemplateItem")
                        .WithMany("LoanReviewItems")
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LoanReviewDetail");

                    b.Navigation("ReviewOption");

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewOption", b =>
                {
                    b.HasOne("LoanReviewApi.Core.Models.Reviews.ReviewOptionType", "ReviewOptionType")
                        .WithMany("ReviewOptions")
                        .HasForeignKey("OptionTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReviewOptionType");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewTemplateItem", b =>
                {
                    b.HasOne("LoanReviewApi.Core.Models.Reviews.ReviewOptionType", "OptionType")
                        .WithMany("ReviewTemplateItems")
                        .HasForeignKey("ItemOptionTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LoanReviewApi.Core.Models.Reviews.ReviewTemplate", "ReviewTemplate")
                        .WithMany("ReviewTemplateItems")
                        .HasForeignKey("ItemOptionTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OptionType");

                    b.Navigation("ReviewTemplate");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Users.User", b =>
                {
                    b.HasOne("LoanReviewApi.Core.Models.Users.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanDetail", b =>
                {
                    b.Navigation("LoanReviewDetails");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanDetailsComm", b =>
                {
                    b.Navigation("LoanReviewDetails");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanReviewDetail", b =>
                {
                    b.Navigation("LoanReviewItems");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Loans.LoanReviewStatus", b =>
                {
                    b.Navigation("LoanReviewDetails");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewOption", b =>
                {
                    b.Navigation("LoanReviewItems");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewOptionType", b =>
                {
                    b.Navigation("ReviewOptions");

                    b.Navigation("ReviewTemplateItems");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewTemplate", b =>
                {
                    b.Navigation("LoanReviewDetails");

                    b.Navigation("ReviewTemplateItems");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Reviews.ReviewTemplateItem", b =>
                {
                    b.Navigation("LoanReviewItems");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Users.User", b =>
                {
                    b.Navigation("UsersCreatedReviewDetails");

                    b.Navigation("UsersUpdatedReviewDetails");
                });

            modelBuilder.Entity("LoanReviewApi.Core.Models.Users.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
